### ISSUE TITLE
Streaming server not available

### ISSUE THREAD

**Issue by Loukious** [Stremio/stremio-service#37]
Server is running correctly and is receiving the get request when I open the public IP in the browser and is redirecting me to the web interface but it's showing streaming server not available
![image](https://github.com/Stremio/stremio-service/assets/24696530/3a67d55e-a4b8-4bac-90aa-35712a2b7dc0)

**Comment by jaruba** [comment]
what is "public ip"? the server needs HTTPS for all cases where it is not used locally (on the same device)

HTTPS can be enabled to use the server in ur home (through LAN)

if u want to expose the server to the worldwide web, then we do not officially support this, nor offer support for it, the Stremio server is not meant to be exposed to the internet directly, we do not offer SSL certificates and/or domains for this case

**Comment by jaruba** [comment]
yes, the service has this functionality too, just no settings in Stremio Web for it yet

u shouldn't try to replace the server ssl cert with ur's, you should use some http server (like nginx) to add ur SSL cert and then use that http server (nginx in this example) to proxy the local port of the streaming server to the outbound https port

but again, we don't offer support for something like that, as for the device that u say is not working with https, that device is probably creating a ssl cert for a different network then what you are testing, or otherwise it is using DNS servers that may take more time to validate the new stremio.rocks domain for ur IP (it is normally very fast, but can take up to 24h for a new subdomain to be propagated to all DNS providers)

**Comment by Loukious** [comment]
Thanks a lot. This is solved

**Comment by Loukious** [comment]
> you should use some http server (like nginx) to add ur SSL cert and then use that http server (nginx in this example) to proxy the local port of the streaming server to the outbound https port

I just tried this and there was some issue. The stremio web is actually accepting the hostname correctly and marking it as online. The problem is the stremio service is serving stream url using it's internal IP address/port.

**Comment by jaruba** [comment]
@Loukious what u are saying is a bit confusing to me, can u send me screenshots of what made u come to the conclusion that:
> the stremio service is serving stream url using it's internal IP address/port.

**Comment by Loukious** [comment]
@jaruba trying to play a video fails, I click open external player and it downloads a .m3u file. This is the content of the file: 
<img width="478" alt="image" src="https://github.com/Stremio/stremio-service/assets/24696530/e681ad14-a989-4dc1-889a-79f8b8d60022">
as you can see the IP in that file is the local IP of the host machine.

**Comment by jaruba** [comment]
the m3u file and stream are constructed in stremio-web (or maybe stremio-core?), imo that is not a stremio-service issue

**Comment by Loukious** [comment]
@jaruba I investigated more into the issue and I found out that I needed to add the external server IP address as a value in the remoteHttps key inside the settings file which solved the problem.

**Comment by jaruba** [comment]
if it works from stremio desktop and not stremio web, then it sounds like a stremio-web issue

if by "external ip" you mean internet IP (and not LAN IP), then even if that works, extended support for it is not guaranteed, as we only support LAN usage officially
